---
# assuming _image_name variable is defined in call to ansible-playbook
- name: ensure wpt_user is in docker group
  user:
    name: "{{ wpt_user | mandatory }}"
    groups: docker
    append: yes

- name: Add the wptsync user uid as a user in the host
  user:
    name: wptsync
    comment: App user
    uid: "{{ app_uid }}"
    create_home: false

- name: Add the rabbitmq user uid as a user in the host
  user:
    name: rabbitmq
    comment: App rabbitmq user
    uid: "{{ rabbitmq_uid }}"
    create_home: false

- name: ensure git is installed
  yum:
    name: git
    state: latest

- name: checkout latest master in wpt-sync repo
  git:
    repo: "{{ wptsync_repo_url | mandatory }}"
    dest: "{{ wptsync_repo_path | mandatory }}"
    version: "{{ lookup('env','WPT_REV') | default('origin/master') }}"
    depth: 1
    accept_hostkey: yes
    force: yes
  become_user: wpt_user

- name: ensure directories expected by docker container
  file:
    path: "{{ item }}"
    state: directory
    owner: wpt_user
    group: wpt
    mode: 0775
  with_items:
    - "{{ mount_repos | mandatory }}"
    - "{{ mount_workspace| mandatory }}"
    - "{{ mount_workspace| mandatory }}/logs"
    - "{{ mount_data | mandatory }}"
    - "{{ mount_data | mandatory }}/{{ ssh_dir | mandatory }}"

- name: install docker-run helper script
  template:
    src: "{{ item }}.j2"
    dest: "{{ internal_volume | mandatory }}/{{ item }}"
    mode: 0755
  with_items:
    - run_docker.sh
  become_user: wpt_user

- name: install credentials (if environment variables are configured)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: wpt_user
    mode: 0600
  with_items:
    - { src: "{{ _ssh_hgmo }}", dest: "{{ mount_data }}/{{ ssh_dir }}/id_hgmo" }
    - { src: "{{ _ssh_hgmo }}.pub", dest: "{{ mount_data }}/{{ ssh_dir }}/id_hgmo.pub" }
    - { src: "{{ _ssh_github }}", dest: "{{ mount_data }}/{{ ssh_dir }}/id_github" }
    - { src: "{{ _ssh_github }}.pub", dest: "{{ mount_data }}/{{ ssh_dir }}/id_github.pub" }
    - { src: "{{ _credentials }}", dest: "{{ mount_data }}/credentials_prod.ini" }
  when: update_credentials and _credentials and _ssh_github and _ssh_hgmo

- name: chown mount-directories to docker container's UID (this may take a while)
  command: "/usr/bin/chown -R {{ docker_uid }}:{{ docker_uid }} {{ item }}"
  with_items:
    - "{{ mount_repos | mandatory }}"
    - "{{ mount_workspace| mandatory }}"
    - "{{ mount_data }}/{{ ssh_dir }}/id_hgmo"
    - "{{ mount_data }}/{{ ssh_dir }}/id_github"
    - "{{ mount_data }}/credentials_prod.ini"

- name: ensure rabbitmq user can create files in workspace/logs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ mount_workspace| mandatory }}/logs"

- name: ensure rabbitmq user can create files in workspace/logs
  file:
    path: "{{ item }}"
    state: file
    mode: 0664
  with_items:
    - "{{ mount_workspace| mandatory }}/logs/shutdown_err"
    - "{{ mount_workspace| mandatory }}/logs/startup_err"
    - "{{ mount_workspace| mandatory }}/logs/shutdown_log"
    - "{{ mount_workspace| mandatory }}/logs/startup_log"
    - "{{ mount_workspace| mandatory }}/logs/rabbit.log"

- import_tasks: push-docker-img.yml
  when: rebuild
