- name: install docker image
  copy:
    src: "{{ _tempdir | mandatory }}/{{ _image_name }}.tar.bz2"
    dest: "{{ internal_volume }}/{{ _image_name }}.tar.bz2"
    owner: wpt_user
    group: wpt
    mode: 0644

- name: load new docker image from archive
  command: "/usr/bin/docker load -i {{internal_volume}}/{{ _image_name }}.tar.bz2"
  become_user: wpt_user
