dist: trusty
language: python
python:
  - "2.7.14"

jobs:
  include:

    # Job 1: Linters
    - env: python2-linters
      sudo: false
      language: python
      python: "2.7.14"
      install:
        - ./bin/run_docker_dev.sh build --py3 --test
        - sudo chown -R 10001 .
      script:
        - ./bin/run_docker_dev.sh test --py3 --no-pytest

    # Job 2: Unit Tests in Docker env
    - env: docker-wptsync-test-py2
      # Upgrade to newer docker version
      addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      services:
        - docker
      install:
        - ./bin/run_docker_dev.sh build --test
        - sudo chown -R 10001 .
      script:
        - ./bin/run_docker_dev.sh test --no-flake8

    # Job 3: Unit Tests in Python 3 Docker env
    - env: docker-wptsync-test-py3
      # Upgrade to newer docker version
      addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      services:
        - docker
      install:
        - ./bin/run_docker_dev.sh build --py3 --test
        - sudo chown -R 10001 .
      script:
        - ./bin/run_docker_dev.sh test --py3 --no-flake8

    # Job 4: mypy in Python 3 Docker env
    - env: docker-wptsync-mypy-py2
      # Upgrade to newer docker version
      addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      services:
        - docker
      install:
        # Note that mypy always requires py3
        - ./bin/run_docker_dev.sh build --py3 --test
        - sudo chown -R 10001 .
      script:
        - ./bin/run_docker_dev.sh test --py3 --no-flake8 --no-pytest --mypy-2

    # Job 5: mypy in Python 3 Docker env
    - env: docker-wptsync-mypy-py3
      # Upgrade to newer docker version
      addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      services:
        - docker
      install:
        # Note that mypy always requires py3
        - ./bin/run_docker_dev.sh build --py3 --test
        - sudo chown -R 10001 .
      script:
        - ./bin/run_docker_dev.sh test --py3 --no-flake8 --no-pytest --mypy-3

    # Job 4: Static Analysis
    - env: static-analysis
      sudo: false
      language: python
      python: "3.6"
      script:
        - pip install bandit
        - bandit -r sync -ll
